
name: Tao Ren
title: Tao Ren's Blog
email: tour.ren.gz@gmail.com
description: A technology enthusiast.<br/>Expert of Live Streaming.<br/>Full-Stack Engineer(iOS, Android, Ember, Angular, Node, Dev-Opt).
selfie: /assets/images/selfie.jpg
logo: /assets/images/logo.png
baseurl: ""
url: "https://touren.github.io"
github:  touren
linkedin:  taoren
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/

markdown: kramdown

paginate: 10

paginate_path: "/page:num/"

disqus:
  shortname: taoblog

google-analytics: 'UA-102950168-1'
google-cse: '000110185879055609612:xdyjng5hwge'

gems:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dist
