
name: Tao Ren
title: Tao Ren's Blog
email: tour.ren.gz@gmail.com
description: A technology enthusiast.<br/> Expert at Live Streaming, Ember, and Android.
selfie: /assets/images/selfie.jpg
logo: /assets/images/logo.png
baseurl: ""
url: "https://touren.github.io"
github:  touren
linkedin:  taoren


markdown: kramdown

paginate: 10

paginate_path: "/page:num/"

disqus:
  shortname: taoblog

google-analytics: 'UA-102950168-1'
google-cse: '000110185879055609612:xdyjng5hwge'

gems:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dist
